CREATE TABLE `reported_post_comment` ( `id` int(11) NOT NULL AUTO_INCREMENT, `user_id` int(11) NOT NULL, `post_comment_id` int(11) NOT NULL, `status` int(11) NOT NULL DEFAULT 1, `created_at` int(11) NOT NULL, `resolved_at` int(11) DEFAULT NULL, PRIMARY KEY (`id`) ) ENGINE=MyISAM DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci;
CREATE TABLE `reported_story` ( `id` int(11) NOT NULL AUTO_INCREMENT, `user_id` int(11) NOT NULL, `story_id` int(11) NOT NULL, `status` int(11) NOT NULL DEFAULT 1, `created_at` int(11) NOT NULL, `resolved_at` int(11) DEFAULT NULL, PRIMARY KEY (`id`) ) ENGINE=MyISAM DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci;
CREATE TABLE `reported_highlight` ( `id` int(11) NOT NULL AUTO_INCREMENT, `user_id` int(11) NOT NULL, `highlight_id` int(11) NOT NULL, `status` int(11) NOT NULL DEFAULT 1, `created_at` int(11) NOT NULL, `resolved_at` int(11) DEFAULT NULL, PRIMARY KEY (`id`) ) ENGINE=MyISAM DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci;
ALTER TABLE `user` ADD `follower_status` INT NOT NULL DEFAULT '1' COMMENT '1=public, 2=private' AFTER `ad_package_id`, ADD `following_status` INT NOT NULL DEFAULT '1' COMMENT '1=public, 2=private' AFTER `follower_status`;
ALTER TABLE `post_comment` ADD `level` INT NOT NULL DEFAULT '1' AFTER `post_id`, ADD `parent_id` INT NOT NULL DEFAULT '0' AFTER `level`;
ALTER TABLE `comment` ADD `level` INT NOT NULL DEFAULT '1' AFTER `reference_id`, ADD `parent_id` INT NOT NULL DEFAULT '0' AFTER `level`;
ALTER TABLE `campaign_comment` ADD `level` INT NOT NULL DEFAULT '1' AFTER `campaign_id`, ADD `parent_id` INT NOT NULL DEFAULT '0' AFTER `level`;
CREATE TABLE IF NOT EXISTS `reported_content` ( `id` int NOT NULL AUTO_INCREMENT, `type` int NOT NULL DEFAULT '1' COMMENT '1=coupon comment,2=campaign comment', `user_id` int NOT NULL, `reference_id` int NOT NULL, `status` int NOT NULL DEFAULT '1', `created_at` int NOT NULL, `resolved_at` int DEFAULT NULL, PRIMARY KEY (`id`) ) ENGINE=MyISAM AUTO_INCREMENT=2 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
CREATE TABLE IF NOT EXISTS `comment_like` ( `id` int NOT NULL AUTO_INCREMENT, `source_type` int NOT NULL DEFAULT '1' COMMENT '1=post,= CAMPAIGN, 3= copupon', `comment_id` int NOT NULL, `user_id` int NOT NULL, `created_at` int NOT NULL, PRIMARY KEY (`id`) ) ENGINE=MyISAM AUTO_INCREMENT=10 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
ALTER TABLE `setting` ADD `is_photo_video_edit` INT NOT NULL DEFAULT '1' AFTER `is_offer`, ADD `imgly_key` VARCHAR(256) NULL DEFAULT NULL AFTER `is_photo_video_edit`;

